// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that CommandDispatcherReplier does implement messaging.CommandDispatcherReplier.
// If this is not the case, regenerate this file with moq.
var _ messaging.CommandDispatcherReplier = &CommandDispatcherReplier{}

// CommandDispatcherReplier is a mock implementation of messaging.CommandDispatcherReplier.
//
//	func TestSomethingThatUsesCommandDispatcherReplier(t *testing.T) {
//
//		// make and configure a mocked messaging.CommandDispatcherReplier
//		mockedCommandDispatcherReplier := &CommandDispatcherReplier{
//			PublishRequestFunc: func(ctx context.Context, cmd messaging.Command) (messaging.Message, error) {
//				panic("mock out the PublishRequest method")
//			},
//		}
//
//		// use mockedCommandDispatcherReplier in code that requires messaging.CommandDispatcherReplier
//		// and then make assertions.
//
//	}
type CommandDispatcherReplier struct {
	// PublishRequestFunc mocks the PublishRequest method.
	PublishRequestFunc func(ctx context.Context, cmd messaging.Command) (messaging.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// PublishRequest holds details about calls to the PublishRequest method.
		PublishRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd messaging.Command
		}
	}
	lockPublishRequest sync.RWMutex
}

// PublishRequest calls PublishRequestFunc.
func (mock *CommandDispatcherReplier) PublishRequest(ctx context.Context, cmd messaging.Command) (messaging.Message, error) {
	if mock.PublishRequestFunc == nil {
		panic("CommandDispatcherReplier.PublishRequestFunc: method is nil but CommandDispatcherReplier.PublishRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cmd messaging.Command
	}{
		Ctx: ctx,
		Cmd: cmd,
	}
	mock.lockPublishRequest.Lock()
	mock.calls.PublishRequest = append(mock.calls.PublishRequest, callInfo)
	mock.lockPublishRequest.Unlock()
	return mock.PublishRequestFunc(ctx, cmd)
}

// PublishRequestCalls gets all the calls that were made to PublishRequest.
// Check the length with:
//
//	len(mockedCommandDispatcherReplier.PublishRequestCalls())
func (mock *CommandDispatcherReplier) PublishRequestCalls() []struct {
	Ctx context.Context
	Cmd messaging.Command
} {
	var calls []struct {
		Ctx context.Context
		Cmd messaging.Command
	}
	mock.lockPublishRequest.RLock()
	calls = mock.calls.PublishRequest
	mock.lockPublishRequest.RUnlock()
	return calls
}
