// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"sync"

	"github.com/xfrr/go-cqrsify/messaging"
)

// Ensure, that CommandBusReplier does implement messaging.CommandBusReplier.
// If this is not the case, regenerate this file with moq.
var _ messaging.CommandBusReplier = &CommandBusReplier{}

// CommandBusReplier is a mock implementation of messaging.CommandBusReplier.
//
//	func TestSomethingThatUsesCommandBusReplier(t *testing.T) {
//
//		// make and configure a mocked messaging.CommandBusReplier
//		mockedCommandBusReplier := &CommandBusReplier{
//			PublishRequestFunc: func(ctx context.Context, cmd messaging.Command) (messaging.Message, error) {
//				panic("mock out the PublishRequest method")
//			},
//			SubscribeWithReplyFunc: func(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the SubscribeWithReply method")
//			},
//		}
//
//		// use mockedCommandBusReplier in code that requires messaging.CommandBusReplier
//		// and then make assertions.
//
//	}
type CommandBusReplier struct {
	// PublishRequestFunc mocks the PublishRequest method.
	PublishRequestFunc func(ctx context.Context, cmd messaging.Command) (messaging.Message, error)

	// SubscribeWithReplyFunc mocks the SubscribeWithReply method.
	SubscribeWithReplyFunc func(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// PublishRequest holds details about calls to the PublishRequest method.
		PublishRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Cmd is the cmd argument value.
			Cmd messaging.Command
		}
		// SubscribeWithReply holds details about calls to the SubscribeWithReply method.
		SubscribeWithReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handler is the handler argument value.
			Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
		}
	}
	lockPublishRequest     sync.RWMutex
	lockSubscribeWithReply sync.RWMutex
}

// DispatchRequest calls PublishRequestFunc.
func (mock *CommandBusReplier) DispatchRequest(ctx context.Context, cmd messaging.Command) (messaging.Message, error) {
	if mock.PublishRequestFunc == nil {
		panic("CommandBusReplier.PublishRequestFunc: method is nil but CommandBusReplier.PublishRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Cmd messaging.Command
	}{
		Ctx: ctx,
		Cmd: cmd,
	}
	mock.lockPublishRequest.Lock()
	mock.calls.PublishRequest = append(mock.calls.PublishRequest, callInfo)
	mock.lockPublishRequest.Unlock()
	return mock.PublishRequestFunc(ctx, cmd)
}

// PublishRequestCalls gets all the calls that were made to PublishRequest.
// Check the length with:
//
//	len(mockedCommandBusReplier.PublishRequestCalls())
func (mock *CommandBusReplier) PublishRequestCalls() []struct {
	Ctx context.Context
	Cmd messaging.Command
} {
	var calls []struct {
		Ctx context.Context
		Cmd messaging.Command
	}
	mock.lockPublishRequest.RLock()
	calls = mock.calls.PublishRequest
	mock.lockPublishRequest.RUnlock()
	return calls
}

// SubscribeWithReply calls SubscribeWithReplyFunc.
func (mock *CommandBusReplier) SubscribeWithReply(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeWithReplyFunc == nil {
		panic("CommandBusReplier.SubscribeWithReplyFunc: method is nil but CommandBusReplier.SubscribeWithReply was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
	}{
		Ctx:     ctx,
		Handler: handler,
	}
	mock.lockSubscribeWithReply.Lock()
	mock.calls.SubscribeWithReply = append(mock.calls.SubscribeWithReply, callInfo)
	mock.lockSubscribeWithReply.Unlock()
	return mock.SubscribeWithReplyFunc(ctx, handler)
}

// SubscribeWithReplyCalls gets all the calls that were made to SubscribeWithReply.
// Check the length with:
//
//	len(mockedCommandBusReplier.SubscribeWithReplyCalls())
func (mock *CommandBusReplier) SubscribeWithReplyCalls() []struct {
	Ctx     context.Context
	Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
} {
	var calls []struct {
		Ctx     context.Context
		Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
	}
	mock.lockSubscribeWithReply.RLock()
	calls = mock.calls.SubscribeWithReply
	mock.lockSubscribeWithReply.RUnlock()
	return calls
}
