// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that CommandConsumerReplier does implement messaging.CommandConsumerReplier.
// If this is not the case, regenerate this file with moq.
var _ messaging.CommandConsumerReplier = &CommandConsumerReplier{}

// CommandConsumerReplier is a mock implementation of messaging.CommandConsumerReplier.
//
//	func TestSomethingThatUsesCommandConsumerReplier(t *testing.T) {
//
//		// make and configure a mocked messaging.CommandConsumerReplier
//		mockedCommandConsumerReplier := &CommandConsumerReplier{
//			SubscribeWithReplyFunc: func(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the SubscribeWithReply method")
//			},
//		}
//
//		// use mockedCommandConsumerReplier in code that requires messaging.CommandConsumerReplier
//		// and then make assertions.
//
//	}
type CommandConsumerReplier struct {
	// SubscribeWithReplyFunc mocks the SubscribeWithReply method.
	SubscribeWithReplyFunc func(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// SubscribeWithReply holds details about calls to the SubscribeWithReply method.
		SubscribeWithReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Handler is the handler argument value.
			Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
		}
	}
	lockSubscribeWithReply sync.RWMutex
}

// SubscribeWithReply calls SubscribeWithReplyFunc.
func (mock *CommandConsumerReplier) SubscribeWithReply(ctx context.Context, handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeWithReplyFunc == nil {
		panic("CommandConsumerReplier.SubscribeWithReplyFunc: method is nil but CommandConsumerReplier.SubscribeWithReply was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
	}{
		Ctx:     ctx,
		Handler: handler,
	}
	mock.lockSubscribeWithReply.Lock()
	mock.calls.SubscribeWithReply = append(mock.calls.SubscribeWithReply, callInfo)
	mock.lockSubscribeWithReply.Unlock()
	return mock.SubscribeWithReplyFunc(ctx, handler)
}

// SubscribeWithReplyCalls gets all the calls that were made to SubscribeWithReply.
// Check the length with:
//
//	len(mockedCommandConsumerReplier.SubscribeWithReplyCalls())
func (mock *CommandConsumerReplier) SubscribeWithReplyCalls() []struct {
	Ctx     context.Context
	Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
} {
	var calls []struct {
		Ctx     context.Context
		Handler messaging.MessageHandlerWithReply[messaging.Command, messaging.CommandReply]
	}
	mock.lockSubscribeWithReply.RLock()
	calls = mock.calls.SubscribeWithReply
	mock.lockSubscribeWithReply.RUnlock()
	return calls
}
