// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that CommandBus does implement messaging.CommandBus.
// If this is not the case, regenerate this file with moq.
var _ messaging.CommandBus = &CommandBus{}

// CommandBus is a mock implementation of messaging.CommandBus.
//
//	func TestSomethingThatUsesCommandBus(t *testing.T) {
//
//		// make and configure a mocked messaging.CommandBus
//		mockedCommandBus := &CommandBus{
//			DispatchFunc: func(ctx context.Context, commands ...messaging.Command) error {
//				panic("mock out the Dispatch method")
//			},
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandler[messaging.Command]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedCommandBus in code that requires messaging.CommandBus
//		// and then make assertions.
//
//	}
type CommandBus struct {
	// DispatchFunc mocks the Dispatch method.
	DispatchFunc func(ctx context.Context, commands ...messaging.Command) error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandler[messaging.Command]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Dispatch holds details about calls to the Dispatch method.
		Dispatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Commands is the commands argument value.
			Commands []messaging.Command
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandler[messaging.Command]
		}
	}
	lockDispatch  sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Dispatch calls DispatchFunc.
func (mock *CommandBus) Dispatch(ctx context.Context, commands ...messaging.Command) error {
	if mock.DispatchFunc == nil {
		panic("CommandBus.DispatchFunc: method is nil but CommandBus.Dispatch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Commands []messaging.Command
	}{
		Ctx:      ctx,
		Commands: commands,
	}
	mock.lockDispatch.Lock()
	mock.calls.Dispatch = append(mock.calls.Dispatch, callInfo)
	mock.lockDispatch.Unlock()
	return mock.DispatchFunc(ctx, commands...)
}

// DispatchCalls gets all the calls that were made to Dispatch.
// Check the length with:
//
//	len(mockedCommandBus.DispatchCalls())
func (mock *CommandBus) DispatchCalls() []struct {
	Ctx      context.Context
	Commands []messaging.Command
} {
	var calls []struct {
		Ctx      context.Context
		Commands []messaging.Command
	}
	mock.lockDispatch.RLock()
	calls = mock.calls.Dispatch
	mock.lockDispatch.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *CommandBus) Subscribe(ctx context.Context, h messaging.MessageHandler[messaging.Command]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("CommandBus.SubscribeFunc: method is nil but CommandBus.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Command]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedCommandBus.SubscribeCalls())
func (mock *CommandBus) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandler[messaging.Command]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Command]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
