// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that CommandDispatcher does implement messaging.CommandDispatcher.
// If this is not the case, regenerate this file with moq.
var _ messaging.CommandDispatcher = &CommandDispatcher{}

// CommandDispatcher is a mock implementation of messaging.CommandDispatcher.
//
//	func TestSomethingThatUsesCommandDispatcher(t *testing.T) {
//
//		// make and configure a mocked messaging.CommandDispatcher
//		mockedCommandDispatcher := &CommandDispatcher{
//			DispatchFunc: func(ctx context.Context, commands ...messaging.Command) error {
//				panic("mock out the Dispatch method")
//			},
//		}
//
//		// use mockedCommandDispatcher in code that requires messaging.CommandDispatcher
//		// and then make assertions.
//
//	}
type CommandDispatcher struct {
	// DispatchFunc mocks the Dispatch method.
	DispatchFunc func(ctx context.Context, commands ...messaging.Command) error

	// calls tracks calls to the methods.
	calls struct {
		// Dispatch holds details about calls to the Dispatch method.
		Dispatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Commands is the commands argument value.
			Commands []messaging.Command
		}
	}
	lockDispatch sync.RWMutex
}

// Dispatch calls DispatchFunc.
func (mock *CommandDispatcher) Dispatch(ctx context.Context, commands ...messaging.Command) error {
	if mock.DispatchFunc == nil {
		panic("CommandDispatcher.DispatchFunc: method is nil but CommandDispatcher.Dispatch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Commands []messaging.Command
	}{
		Ctx:      ctx,
		Commands: commands,
	}
	mock.lockDispatch.Lock()
	mock.calls.Dispatch = append(mock.calls.Dispatch, callInfo)
	mock.lockDispatch.Unlock()
	return mock.DispatchFunc(ctx, commands...)
}

// DispatchCalls gets all the calls that were made to Dispatch.
// Check the length with:
//
//	len(mockedCommandDispatcher.DispatchCalls())
func (mock *CommandDispatcher) DispatchCalls() []struct {
	Ctx      context.Context
	Commands []messaging.Command
} {
	var calls []struct {
		Ctx      context.Context
		Commands []messaging.Command
	}
	mock.lockDispatch.RLock()
	calls = mock.calls.Dispatch
	mock.lockDispatch.RUnlock()
	return calls
}
