// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that EventConsumer does implement messaging.EventConsumer.
// If this is not the case, regenerate this file with moq.
var _ messaging.EventConsumer = &EventConsumer{}

// EventConsumer is a mock implementation of messaging.EventConsumer.
//
//	func TestSomethingThatUsesEventConsumer(t *testing.T) {
//
//		// make and configure a mocked messaging.EventConsumer
//		mockedEventConsumer := &EventConsumer{
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedEventConsumer in code that requires messaging.EventConsumer
//		// and then make assertions.
//
//	}
type EventConsumer struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandler[messaging.Event]
		}
	}
	lockSubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *EventConsumer) Subscribe(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("EventConsumer.SubscribeFunc: method is nil but EventConsumer.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Event]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedEventConsumer.SubscribeCalls())
func (mock *EventConsumer) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandler[messaging.Event]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Event]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
