// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that EventPublisher does implement messaging.EventPublisher.
// If this is not the case, regenerate this file with moq.
var _ messaging.EventPublisher = &EventPublisher{}

// EventPublisher is a mock implementation of messaging.EventPublisher.
//
//	func TestSomethingThatUsesEventPublisher(t *testing.T) {
//
//		// make and configure a mocked messaging.EventPublisher
//		mockedEventPublisher := &EventPublisher{
//			PublishFunc: func(ctx context.Context, events ...messaging.Event) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedEventPublisher in code that requires messaging.EventPublisher
//		// and then make assertions.
//
//	}
type EventPublisher struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, events ...messaging.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Events is the events argument value.
			Events []messaging.Event
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *EventPublisher) Publish(ctx context.Context, events ...messaging.Event) error {
	if mock.PublishFunc == nil {
		panic("EventPublisher.PublishFunc: method is nil but EventPublisher.Publish was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Events []messaging.Event
	}{
		Ctx:    ctx,
		Events: events,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, events...)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedEventPublisher.PublishCalls())
func (mock *EventPublisher) PublishCalls() []struct {
	Ctx    context.Context
	Events []messaging.Event
} {
	var calls []struct {
		Ctx    context.Context
		Events []messaging.Event
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
