// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that EventBus does implement messaging.EventBus.
// If this is not the case, regenerate this file with moq.
var _ messaging.EventBus = &EventBus{}

// EventBus is a mock implementation of messaging.EventBus.
//
//	func TestSomethingThatUsesEventBus(t *testing.T) {
//
//		// make and configure a mocked messaging.EventBus
//		mockedEventBus := &EventBus{
//			PublishFunc: func(ctx context.Context, events ...messaging.Event) error {
//				panic("mock out the Publish method")
//			},
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedEventBus in code that requires messaging.EventBus
//		// and then make assertions.
//
//	}
type EventBus struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, events ...messaging.Event) error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Events is the events argument value.
			Events []messaging.Event
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandler[messaging.Event]
		}
	}
	lockPublish   sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *EventBus) Publish(ctx context.Context, events ...messaging.Event) error {
	if mock.PublishFunc == nil {
		panic("EventBus.PublishFunc: method is nil but EventBus.Publish was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Events []messaging.Event
	}{
		Ctx:    ctx,
		Events: events,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, events...)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedEventBus.PublishCalls())
func (mock *EventBus) PublishCalls() []struct {
	Ctx    context.Context
	Events []messaging.Event
} {
	var calls []struct {
		Ctx    context.Context
		Events []messaging.Event
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *EventBus) Subscribe(ctx context.Context, h messaging.MessageHandler[messaging.Event]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("EventBus.SubscribeFunc: method is nil but EventBus.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Event]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedEventBus.SubscribeCalls())
func (mock *EventBus) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandler[messaging.Event]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Event]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
