// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that MessagePublisher does implement messaging.MessagePublisher.
// If this is not the case, regenerate this file with moq.
var _ messaging.MessagePublisher = &MessagePublisher{}

// MessagePublisher is a mock implementation of messaging.MessagePublisher.
//
//	func TestSomethingThatUsesMessagePublisher(t *testing.T) {
//
//		// make and configure a mocked messaging.MessagePublisher
//		mockedMessagePublisher := &MessagePublisher{
//			PublishFunc: func(ctx context.Context, messages ...messaging.Message) error {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedMessagePublisher in code that requires messaging.MessagePublisher
//		// and then make assertions.
//
//	}
type MessagePublisher struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, messages ...messaging.Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Messages is the messages argument value.
			Messages []messaging.Message
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *MessagePublisher) Publish(ctx context.Context, messages ...messaging.Message) error {
	if mock.PublishFunc == nil {
		panic("MessagePublisher.PublishFunc: method is nil but MessagePublisher.Publish was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Messages []messaging.Message
	}{
		Ctx:      ctx,
		Messages: messages,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, messages...)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedMessagePublisher.PublishCalls())
func (mock *MessagePublisher) PublishCalls() []struct {
	Ctx      context.Context
	Messages []messaging.Message
} {
	var calls []struct {
		Ctx      context.Context
		Messages []messaging.Message
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
