// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that MessageConsumer does implement messaging.MessageConsumer.
// If this is not the case, regenerate this file with moq.
var _ messaging.MessageConsumer = &MessageConsumer{}

// MessageConsumer is a mock implementation of messaging.MessageConsumer.
//
//	func TestSomethingThatUsesMessageConsumer(t *testing.T) {
//
//		// make and configure a mocked messaging.MessageConsumer
//		mockedMessageConsumer := &MessageConsumer{
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandler[messaging.Message]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedMessageConsumer in code that requires messaging.MessageConsumer
//		// and then make assertions.
//
//	}
type MessageConsumer struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandler[messaging.Message]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandler[messaging.Message]
		}
	}
	lockSubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *MessageConsumer) Subscribe(ctx context.Context, h messaging.MessageHandler[messaging.Message]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("MessageConsumer.SubscribeFunc: method is nil but MessageConsumer.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Message]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedMessageConsumer.SubscribeCalls())
func (mock *MessageConsumer) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandler[messaging.Message]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandler[messaging.Message]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
