// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that MessageConsumerReplier does implement messaging.MessageConsumerReplier.
// If this is not the case, regenerate this file with moq.
var _ messaging.MessageConsumerReplier = &MessageConsumerReplier{}

// MessageConsumerReplier is a mock implementation of messaging.MessageConsumerReplier.
//
//	func TestSomethingThatUsesMessageConsumerReplier(t *testing.T) {
//
//		// make and configure a mocked messaging.MessageConsumerReplier
//		mockedMessageConsumerReplier := &MessageConsumerReplier{
//			SubscribeWithReplyFunc: func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the SubscribeWithReply method")
//			},
//		}
//
//		// use mockedMessageConsumerReplier in code that requires messaging.MessageConsumerReplier
//		// and then make assertions.
//
//	}
type MessageConsumerReplier struct {
	// SubscribeWithReplyFunc mocks the SubscribeWithReply method.
	SubscribeWithReplyFunc func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// SubscribeWithReply holds details about calls to the SubscribeWithReply method.
		SubscribeWithReply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]
		}
	}
	lockSubscribeWithReply sync.RWMutex
}

// SubscribeWithReply calls SubscribeWithReplyFunc.
func (mock *MessageConsumerReplier) SubscribeWithReply(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeWithReplyFunc == nil {
		panic("MessageConsumerReplier.SubscribeWithReplyFunc: method is nil but MessageConsumerReplier.SubscribeWithReply was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribeWithReply.Lock()
	mock.calls.SubscribeWithReply = append(mock.calls.SubscribeWithReply, callInfo)
	mock.lockSubscribeWithReply.Unlock()
	return mock.SubscribeWithReplyFunc(ctx, h)
}

// SubscribeWithReplyCalls gets all the calls that were made to SubscribeWithReply.
// Check the length with:
//
//	len(mockedMessageConsumerReplier.SubscribeWithReplyCalls())
func (mock *MessageConsumerReplier) SubscribeWithReplyCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Message, messaging.Message]
	}
	mock.lockSubscribeWithReply.RLock()
	calls = mock.calls.SubscribeWithReply
	mock.lockSubscribeWithReply.RUnlock()
	return calls
}
