// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that MessagePublisherReplier does implement messaging.MessagePublisherReplier.
// If this is not the case, regenerate this file with moq.
var _ messaging.MessagePublisherReplier = &MessagePublisherReplier{}

// MessagePublisherReplier is a mock implementation of messaging.MessagePublisherReplier.
//
//	func TestSomethingThatUsesMessagePublisherReplier(t *testing.T) {
//
//		// make and configure a mocked messaging.MessagePublisherReplier
//		mockedMessagePublisherReplier := &MessagePublisherReplier{
//			PublishRequestFunc: func(ctx context.Context, msg messaging.Message) (messaging.Message, error) {
//				panic("mock out the PublishRequest method")
//			},
//		}
//
//		// use mockedMessagePublisherReplier in code that requires messaging.MessagePublisherReplier
//		// and then make assertions.
//
//	}
type MessagePublisherReplier struct {
	// PublishRequestFunc mocks the PublishRequest method.
	PublishRequestFunc func(ctx context.Context, msg messaging.Message) (messaging.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// PublishRequest holds details about calls to the PublishRequest method.
		PublishRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg messaging.Message
		}
	}
	lockPublishRequest sync.RWMutex
}

// PublishRequest calls PublishRequestFunc.
func (mock *MessagePublisherReplier) PublishRequest(ctx context.Context, msg messaging.Message) (messaging.Message, error) {
	if mock.PublishRequestFunc == nil {
		panic("MessagePublisherReplier.PublishRequestFunc: method is nil but MessagePublisherReplier.PublishRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg messaging.Message
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockPublishRequest.Lock()
	mock.calls.PublishRequest = append(mock.calls.PublishRequest, callInfo)
	mock.lockPublishRequest.Unlock()
	return mock.PublishRequestFunc(ctx, msg)
}

// PublishRequestCalls gets all the calls that were made to PublishRequest.
// Check the length with:
//
//	len(mockedMessagePublisherReplier.PublishRequestCalls())
func (mock *MessagePublisherReplier) PublishRequestCalls() []struct {
	Ctx context.Context
	Msg messaging.Message
} {
	var calls []struct {
		Ctx context.Context
		Msg messaging.Message
	}
	mock.lockPublishRequest.RLock()
	calls = mock.calls.PublishRequest
	mock.lockPublishRequest.RUnlock()
	return calls
}
