// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that QueryDispatcher does implement messaging.QueryDispatcher.
// If this is not the case, regenerate this file with moq.
var _ messaging.QueryDispatcher = &QueryDispatcher{}

// QueryDispatcher is a mock implementation of messaging.QueryDispatcher.
//
//	func TestSomethingThatUsesQueryDispatcher(t *testing.T) {
//
//		// make and configure a mocked messaging.QueryDispatcher
//		mockedQueryDispatcher := &QueryDispatcher{
//			RequestFunc: func(ctx context.Context, qry messaging.Query) (messaging.Message, error) {
//				panic("mock out the Request method")
//			},
//		}
//
//		// use mockedQueryDispatcher in code that requires messaging.QueryDispatcher
//		// and then make assertions.
//
//	}
type QueryDispatcher struct {
	// RequestFunc mocks the Request method.
	RequestFunc func(ctx context.Context, qry messaging.Query) (messaging.Message, error)

	// calls tracks calls to the methods.
	calls struct {
		// Request holds details about calls to the Request method.
		Request []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Qry is the qry argument value.
			Qry messaging.Query
		}
	}
	lockRequest sync.RWMutex
}

// Request calls RequestFunc.
func (mock *QueryDispatcher) Request(ctx context.Context, qry messaging.Query) (messaging.Message, error) {
	if mock.RequestFunc == nil {
		panic("QueryDispatcher.RequestFunc: method is nil but QueryDispatcher.Request was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Qry messaging.Query
	}{
		Ctx: ctx,
		Qry: qry,
	}
	mock.lockRequest.Lock()
	mock.calls.Request = append(mock.calls.Request, callInfo)
	mock.lockRequest.Unlock()
	return mock.RequestFunc(ctx, qry)
}

// RequestCalls gets all the calls that were made to Request.
// Check the length with:
//
//	len(mockedQueryDispatcher.RequestCalls())
func (mock *QueryDispatcher) RequestCalls() []struct {
	Ctx context.Context
	Qry messaging.Query
} {
	var calls []struct {
		Ctx context.Context
		Qry messaging.Query
	}
	mock.lockRequest.RLock()
	calls = mock.calls.Request
	mock.lockRequest.RUnlock()
	return calls
}
