// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that QueryConsumer does implement messaging.QueryConsumer.
// If this is not the case, regenerate this file with moq.
var _ messaging.QueryConsumer = &QueryConsumer{}

// QueryConsumer is a mock implementation of messaging.QueryConsumer.
//
//	func TestSomethingThatUsesQueryConsumer(t *testing.T) {
//
//		// make and configure a mocked messaging.QueryConsumer
//		mockedQueryConsumer := &QueryConsumer{
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedQueryConsumer in code that requires messaging.QueryConsumer
//		// and then make assertions.
//
//	}
type QueryConsumer struct {
	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
		}
	}
	lockSubscribe sync.RWMutex
}

// Subscribe calls SubscribeFunc.
func (mock *QueryConsumer) Subscribe(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("QueryConsumer.SubscribeFunc: method is nil but QueryConsumer.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedQueryConsumer.SubscribeCalls())
func (mock *QueryConsumer) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
