// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package messagingmock

import (
	"context"
	"github.com/xfrr/go-cqrsify/messaging"
	"sync"
)

// Ensure, that QueryBus does implement messaging.QueryBus.
// If this is not the case, regenerate this file with moq.
var _ messaging.QueryBus = &QueryBus{}

// QueryBus is a mock implementation of messaging.QueryBus.
//
//	func TestSomethingThatUsesQueryBus(t *testing.T) {
//
//		// make and configure a mocked messaging.QueryBus
//		mockedQueryBus := &QueryBus{
//			RequestFunc: func(ctx context.Context, qry messaging.Query) (messaging.Message, error) {
//				panic("mock out the Request method")
//			},
//			SubscribeFunc: func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error) {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedQueryBus in code that requires messaging.QueryBus
//		// and then make assertions.
//
//	}
type QueryBus struct {
	// RequestFunc mocks the Request method.
	RequestFunc func(ctx context.Context, qry messaging.Query) (messaging.Message, error)

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error)

	// calls tracks calls to the methods.
	calls struct {
		// Request holds details about calls to the Request method.
		Request []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Qry is the qry argument value.
			Qry messaging.Query
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// H is the h argument value.
			H messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
		}
	}
	lockRequest   sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Request calls RequestFunc.
func (mock *QueryBus) Request(ctx context.Context, qry messaging.Query) (messaging.Message, error) {
	if mock.RequestFunc == nil {
		panic("QueryBus.RequestFunc: method is nil but QueryBus.Request was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Qry messaging.Query
	}{
		Ctx: ctx,
		Qry: qry,
	}
	mock.lockRequest.Lock()
	mock.calls.Request = append(mock.calls.Request, callInfo)
	mock.lockRequest.Unlock()
	return mock.RequestFunc(ctx, qry)
}

// RequestCalls gets all the calls that were made to Request.
// Check the length with:
//
//	len(mockedQueryBus.RequestCalls())
func (mock *QueryBus) RequestCalls() []struct {
	Ctx context.Context
	Qry messaging.Query
} {
	var calls []struct {
		Ctx context.Context
		Qry messaging.Query
	}
	mock.lockRequest.RLock()
	calls = mock.calls.Request
	mock.lockRequest.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *QueryBus) Subscribe(ctx context.Context, h messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]) (messaging.UnsubscribeFunc, error) {
	if mock.SubscribeFunc == nil {
		panic("QueryBus.SubscribeFunc: method is nil but QueryBus.Subscribe was just called")
	}
	callInfo := struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
	}{
		Ctx: ctx,
		H:   h,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, h)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedQueryBus.SubscribeCalls())
func (mock *QueryBus) SubscribeCalls() []struct {
	Ctx context.Context
	H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
} {
	var calls []struct {
		Ctx context.Context
		H   messaging.MessageHandlerWithReply[messaging.Query, messaging.QueryReply]
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
